Data Cleaning of geolocation and customers

In [2]:
import numpy as np
import pandas as pd

In [5]:
path = "data/olist_geolocation_dataset.csv"
geo = pd.read_csv(path, sep='\t')

In [6]:
customers = pd.read_csv("data/olist_customers_dataset.csv", sep='\t')

In [3]:
geo.shape

(1000163, 5)

In [5]:
customers.shape

(99441, 5)

In [6]:
geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [7]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [8]:
geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [9]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [10]:
geo.describe

<bound method NDFrame.describe of          geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                               1037       -23.545621       -46.639292
1                               1046       -23.546081       -46.644820
2                               1046       -23.546129       -46.642951
3                               1041       -23.544392       -46.639499
4                               1035       -23.541578       -46.641607
...                              ...              ...              ...
1000158                        99950       -28.068639       -52.010705
1000159                        99900       -27.877125       -52.224882
1000160                        99950       -28.071855       -52.014716
1000161                        99980       -28.388932       -51.846871
1000162                        99950       -28.070104       -52.018658

        geolocation_city geolocation_state
0              sao paulo                SP
1              sao paulo                SP
2              sao paulo                SP
3              sao paulo                SP
4              sao paulo                SP
...                  ...               ...
1000158         tapejara                RS
1000159   getulio vargas                RS
1000160         tapejara                RS
1000161  david canabarro                RS
1000162         tapejara                RS

[1000163 rows x 5 columns]>

In [11]:
customers.describe

<bound method NDFrame.describe of                             customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 5 columns]>

In [12]:
geo.isnull().sum().sum()

np.int64(0)

In [13]:
customers.isnull().sum().sum()

np.int64(0)

In [ ]:
geo_d=geo.duplicated().sum()
print(geo_d)

261831

In [15]:
customers_d = customers.duplicated().sum()
print(customers_d)

0

Data Cleaning of order_items

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
order_items = pd.read_csv("data/olist_order_items_dataset.csv", sep='\t')
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [7]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [10]:
order_items['freight_value'].describe()

count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

In [13]:
order_items.duplicated().value_counts()

False    112650
Name: count, dtype: int64

Data Preparation of order_payments

In [ ]:
order_payments = pd.read_csv("data/olist_order_payments_dataset.csv", sep='\t')
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [15]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [17]:
order_payments.duplicated().value_counts()

False    103886
Name: count, dtype: int64

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [ ]:
product_df = pd.read_csv("data/olist_products_dataset.csv", sep='\t')
seller_df = pd.read_csv("data/olist/sellers_dataset.csv", sep='\t')

Product dataset cleaning

In [5]:
product_df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [12]:
product_df.shape

(32340, 9)

In [9]:
product_df = product_df.dropna()
product_df.shape

(32340, 9)

In [13]:
product_df = product_df.drop_duplicates()

product_df.shape

(32340, 9)

Seller dataset cleaning

In [16]:
seller_df.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [17]:
seller_df.shape

(3095, 4)

In [18]:
seller_df = seller_df.dropna()
seller_df.shape

(3095, 4)

In [19]:
seller_df = seller_df.drop_duplicates()

seller_df.shape

(3095, 4)